Sistema_de_Consultas/config/routes.rb
Rails.application.routes.draw do
  get 'controle_usuarios/index'
  get 'administracao/index'
  get 'administrador/index'
  get 'secretaria/index'
  devise_for :usuarios
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  resources :users
  resources :consulta
  resources :pacientes
  resources :medicos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Sistema_de_Consultas/app/controllers/secretaria_controller.rb
class SecretariaController < ApplicationController
	before_action :authenticate_usuario!
  def index
  end
end

Sistema_de_Consultas/app/helpers/secretaria_helper.rb
module SecretariaHelper
end

Sistema_de_Consultas/app/views/secretaria/index.html.erb
<u><h1>Menu de Agendamento e Consulta</h1></u>
<p><b><font color=#4682B4> Seja bem-vindo:  <%= current_usuario.email %> </p></b></font color>


<div>
	 <%= link_to "Agendar consulta", consulta_path, class: "btn btn-lg btn-primary" %>
	 <%= link_to "Cadastro de pacientes", pacientes_path, class: "btn btn-lg btn-primary" %>
	 <%= link_to "Cadastro de Médicos", medicos_path, class: "btn btn-lg btn-primary" %>
	 <%= link_to "Listagem de Usuarios", controle_usuarios_index_path, class: "btn btn-lg btn-primary" %>
	 <%= link_to "Sair", destroy_usuario_session_path, method: :delete, class: "btn btn-lg btn-primary" %>
</div>