Sistema_de_Consultas/config/routes.rb
Rails.application.routes.draw do
  get 'controle_usuarios/index'
  get 'administracao/index'
  get 'administrador/index'
  get 'secretaria/index'
  devise_for :usuarios
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  resources :users
  resources :consulta
  resources :pacientes
  resources :medicos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Sistema_de_Consultas/app/models/usuario.rb
class Usuario < ApplicationRecord

	enum role: [:Secretario, :Administrador]
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
end

Sistema_de_Consultas/app/views/usuarios/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Entrar", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Cadastre-se", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Esqueceu sua senha?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Não recebeu as instruções de confirmação?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Não recebeu as instruções de desbloqueio?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Entrar com #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>