Sistema_de_Consultas/config/routes.rb
Rails.application.routes.draw do
  get 'controle_usuarios/index'
  get 'administracao/index'
  get 'administrador/index'
  get 'secretaria/index'
  devise_for :usuarios
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  resources :users
  resources :consulta
  resources :pacientes
  resources :medicos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Sistema_de_Consultas/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

Sistema_de_Consultas/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

Sistema_de_Consultas/app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<font color=#4682B4>
<h1><u>Hospital do Gama</u></h1>
<p>
  <font size=5>O <b>Hospital do Gama</b> tem uma estrutura ampla, moderna e confortável, 
  que concentra consultórios médicos e clínicas especializadas.</font size>
</p>
<br>
</br>
<p>
Localizado em frente à Universidade de Brasília(UnB - FGA), possui convênio com mais de 60 planos de saúde e é referência de atendimento
em mais de 18 especialidades.
</p>
<br>
</br>

<b><font size=4>Central de Agendamento de Consultas:</font size></b>
<br/>
<br/>
<p>
<b>(61) 3704-9006 / 3704-9007</b><br/>
Domingo a domingo, das 7h às 19h
</p>

<br/>
<br/>
<b><font size=4>Horário de Atendimento para consultas:</font size></b>
<br/>
<br/>
<p>
Segunda a quinta, das 8h às 18h | Sexta, das 8h às 17h
</p>

<br/>
<br/>
<b><font size=4>Endereço:</font size></b>
<br/>
<br/>
<p>
St. Leste Projeção H - Gama Leste, Brasília - DF, 72444-240 (Em frente à Universidade de Brasília(UnB - Gama))
</p>

<br/>
<br/>
<b><font size=4>Especialidades médicas atendidas:</font size></b>
<br/>
<br/>
<b><font size=3>Adulto</font size></b>
<br/>
<br/>
<ul>
<li>Cardiologia</li>
<li>Cirurgia de Cabeça e Pescoço</li>
<li>Cirurgia Geral</li>
<li>Cirurgia Oncológica e do Aparelho Digestivo</li>
<li>Cirurgia Vascular</li>
<li>Cirurgia Plástica</li>
<li>Clínica Médica</li>
<li>Dermatologia</li>
<li>Endocrinologia</li>
<li>Gastroenterologia</li>
<li>Ginecologia</li>
<li>Hematologia</li>
<li>Hepatologia</li>
<li>Mastologia</li>
<li>Medicina do Viajante</li>
<li>Nefrologia</li>
<li>Neurologia</li>
<li>Nutrologia</li>
<li>Oncologia Clínica</li>
<li>Ortopedia</li>
</ul>
<br/>
<br/>
<b><font size=3>Pediátricas</font size></b></b>
<br/>
<br/>
<ul>
<li>Alergologia</li>
<li>Cirurgia Pediátrica</li>
<li>Gastroenterologia</li>
<li>Neurologia</li>
<li>Nutrologia</li>
<li>Ortopedia</li>
<li>Pediatria Geral</li>
</ul>



</font color>

Sistema_de_Consultas/app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<font color=#4682B4>
<u><h1>Contatos</h1></u>
<p>
  <font size=4>
  <b>CENTRAL DE ATENDIMENTO</b>
  </font>
  <br>
  <b>(61) 3301-8909</b>
  <br>
  <br>
  <br>
    <font size=4>
      <b>CENTRAL DE AUTORIZAÇÃO</b>
    </font>
    <br>
      <b>(61) 3704-9000 - Opção 1 e depois opção 1</b>
    <br>
    <br>
    <br>
    <font size=4><font color="">
      <b>AGENDAMENTO CIRÚRGICO</b>
    </font> </font>
    <br>
      <b>(61) 3704-9000</b>
    <br>
</p>

</font color>

Sistema_de_Consultas/app/views/static_pages/help.html.erb
<% provide(:title, "Trabalhe Conosco") %>
<font color=#4682B4><u><h1>Trabalhe Conosco</h1></u>
<p>
<font size=4><b>Venha fazer parte do nosso time!</b></font size>
<br/>
<br/>
<b><font size=4>Nós, do Hospital do Gama, ficamos felizes que você queira fazer parte de nosso time. Agende uma entrevista ligando para o número (61) 3389-4934 e traga seu currículo.</b>
</font size>
</p>
</font color>

Sistema_de_Consultas/app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>  <font color=#4682B4> Seja bem-vindo ao hospital do Gama </font color> </h1> 

  <h2>
     AGENDE UMA CONSULTA
    
  </h2>
  	<% if usuario_signed_in? %>
 		<%=  link_to "Sair", destroy_usuario_session_path, method: :delete, class: "btn btn-lg btn-primary" %>	
 		<%=  link_to "Menu", secretaria_index_path, class: "btn btn-lg btn-primary" %>	

 	<% else %>
 		<%= link_to "Entrar", secretaria_index_path, class: "btn btn-lg btn-primary" %>
 		<%=  link_to "Cadastre-se", new_usuario_registration_path, class: "btn btn-lg btn-primary" %>
 	<% end %>
  <%#= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
 </div>
 <div>
 </div>