Sistema_de_Consultas/config/routes.rb
Rails.application.routes.draw do
  get 'controle_usuarios/index'
  get 'administracao/index'
  get 'administrador/index'
  get 'secretaria/index'
  devise_for :usuarios
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  resources :users
  resources :consulta
  resources :pacientes
  resources :medicos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Sistema_de_Consultas/app/models/medico.rb
class Medico < ApplicationRecord
  has_many :especializacao
end

Sistema_de_Consultas/app/controllers/medicos_controller.rb
class MedicosController < ApplicationController
  before_action :set_medico, only: [:show, :edit, :update, :destroy]

  # GET /medicos
  # GET /medicos.json
  def index
    @medicos = Medico.all
  end

  # GET /medicos/1
  # GET /medicos/1.json
  def show
  end

  # GET /medicos/new
  def new
    @medico = Medico.new
  end

  # GET /medicos/1/edit
  def edit
  end

  # POST /medicos
  # POST /medicos.json
  def create
    @medico = Medico.new(medico_params)

    respond_to do |format|
      if @medico.save
        format.html { redirect_to @medico, notice: 'O médico foi cadastrado com sucesso' }
        format.json { render :show, status: :created, location: @medico }
      else
        format.html { render :new }
        format.json { render json: @medico.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /medicos/1
  # PATCH/PUT /medicos/1.json
  def update
    respond_to do |format|
      if @medico.update(medico_params)
        format.html { redirect_to @medico, notice: 'A atualização sobre o médico foi efetivada com sucesso' }
        format.json { render :show, status: :ok, location: @medico }
      else
        format.html { render :edit }
        format.json { render json: @medico.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /medicos/1
  # DELETE /medicos/1.json
  def destroy
    @medico.destroy
    respond_to do |format|
      format.html { redirect_to medicos_url, notice: 'O médico foi demitido' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_medico
      @medico = Medico.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def medico_params
      params.require(:medico).permit(:nome, :crm, :especializacao_id)
    end
end

Sistema_de_Consultas/app/helpers/medicos_helper.rb
module MedicosHelper
end

Sistema_de_Consultas/app/views/medicos/_form.html.erb
<%= form_with(model: medico, local: true) do |form| %>
  <% if medico.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(medico.errors.count, "error") %> prohibited this medico from being saved:</h2>

      <ul>
      <% medico.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :"Digite o nome do médico" %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :"Digite o CRM do médico" %>
    <%= form.text_field :crm %>
  </div>

  <div class="field">
    <%= form.label :"Especialização do médico" %>
    <%= form.collection_select(:especializacao_id, Especializacao.all, :id, :name, include_blank: "Selecione a especialização do médico") %>
  </div>

  <div class="actions">
    <%= form.submit "Cadastrar médico", class: "btn btn-primary" %>
  </div>
<% end %>

Sistema_de_Consultas/app/views/medicos/edit.html.erb
<u><h1>Alterando os dados do médico</h1></u>

<%= render 'form', medico: @medico %>

<%= link_to 'Mostrar dados do médico', @medico %> |
<%= link_to 'Voltar', medicos_path %>

Sistema_de_Consultas/app/views/medicos/index.html.erb
<p id="notice"><%= notice %></p>

<u><h1>Médicos</h1></u>

<table>
  <thead>
  <ul>
<li>Nome</li>
<li>CRM</li>
<li>Especialização do médico</li>
</ul>
  </thead>

  <tbody>
    <% @medicos.each do |medico| %>
      <dl>
      <dt><b>Dados do médico</b></dt>
        Nome: <%= medico.nome %></br>
        CRM: <%= medico.crm %></br>
        <dd><%= link_to 'Mostrar os dados do médico', medico %></dd>
        <dd><%= link_to 'Alterar os dados do médico', edit_medico_path(medico) %></dd>
        <dd><%= link_to 'Apagar dados do médico', medico, method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
      </dl>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Cadastrar novo médico', new_medico_path %>

Sistema_de_Consultas/app/views/medicos/new.html.erb
<h1>Cadastrar novo médico</h1>

<%= render 'form', medico: @medico %>

<%= link_to 'Voltar', medicos_path %>

Sistema_de_Consultas/app/views/medicos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @medico.nome %>
</p>

<p>
  <strong>CRM:</strong>
  <%= @medico.crm %>
</p>

<p>
  <strong>Especialização:</strong>
  <%= @medico.especializacao %>
</p>

<%= link_to 'Alterar dados do médico', edit_medico_path(@medico) %> |
<%= link_to 'Voltar', medicos_path %>